apiVersion: v1
kind: Service
metadata:
  labels:
    service: todoapp-frontend
  name: todoapp-frontend
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: todoapp-frontend