apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend
  labels:
    app: todoapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      labels:
        app: todoapp-frontend
    spec:
      containers:
      - name: todoapp-frontend
        image: hiepnnt/todoapp-frontend:v1
        ports:
        - containerPort: 8080